### ISSUE TITLE
google place detail issue

### ISSUE THREAD

**Issue by AstronusX** [anthony-mills/google-places#30]
I have the follow code

 require_once(__DIR__ . '/../../../assets/google/googlePlaces.php');

        $apiKey       = 'xxxx';
        $googlePlaces = new GooglePlaces\googlePlaces($apiKey);
        $googlePlaces->setPlaceId('ChIJ67bX6M6w3IARpKYGn3F-LOc');

        $result = $googlePlaces->details();

and it's return empty, do you know why? can you please help?

**Comment by anthony-mills** [comment]
Hi Mate,
            Are you sure its returning empty and not throwing an error? At a glance the namespace used when instantiating the class is missing part of it. I ran the following code (see below) based on your example against the place id and got back the details for "Joe's Sushi Japanese Restaurant" in California.

I hope that helps...

Cheers

Anthony

<?php
require_once 'src/mills/google-places/googlePlaces.php';

$apiKey = 'Apikey';
$googlePlaces = new Mills\GooglePlaces\googlePlaces($apiKey);
$googlePlaces->setPlaceId('ChIJ67bX6M6w3IARpKYGn3F-LOc');

$result = $googlePlaces->details();

print_r($result);
